version: '3'

services:
  app:
    image: node:14.17.5-alpine3.14
    container_name: its-time-to
    command: sh -c "cd /usr/src/app && npm i && npm run start"
    volumes:
      - .:/usr/src/app
    tty: true
    network_mode: host
